version: '2'
services:
  build:
    image: jetbrainsinfra/golang:1.11.5
    volumes:
      - .:/work
      - modules:/go/pkg/mod
      - cache:/root/.cache
    working_dir: /work
    command: make build -j 3

volumes:
  modules:
  cache:
